### ISSUE TITLE
Build error (Master branch) [Win 10]

### ISSUE THREAD

**Issue by SteveRussell33** [jdstmporter/VCV-Plugins#1]
In file included from src/blocks.cpp:8:
src/blocks.hpp:50:15: warning: 'virtual void haar::Threshold::set(unsigned int, float)' can be marked override [-Wsuggest-override]
   50 |  virtual void set(const unsigned,const float);
      |               ^~~
In file included from src/Haar.cpp:8:
src/Haar.hpp:53:26: error: 'Block' does not name a type
   53 |     void threshold(const Block & mu,const Block & theta);
      |                          ^~~~~
src/Haar.hpp:53:43: error: 'Block' does not name a type
   53 |     void threshold(const Block & mu,const Block & theta);
      |                                           ^~~~~
g++ -std=c++11 -Wsuggest-override  -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/Wavelet.cpp.o src/Wavelet.cpp
src/Haar.cpp: In member function 'float haar::Haar::absMax(unsigned int) const':
src/Haar.cpp:58:49: error: no matching function for call to 'max(int, float&)'
   58 |  return std::max(abs(*pair.first),*(pair.second));
      |                                                 ^
In file included from C:/msys64/mingw64/include/c++/10.1.0/algorithm:61,
                 from src/Haar.hpp:11,
                 from src/Haar.cpp:8:
C:/msys64/mingw64/include/c++/10.1.0/bits/stl_algobase.h:254:5: note: candidate: 'template<class _Tp> const _Tp& std::max(const _Tp&, const _Tp&)'
  254 |     max(const _Tp& __a, const _Tp& __b)
      |     ^~~
C:/msys64/mingw64/include/c++/10.1.0/bits/stl_algobase.h:254:5: note:   template argument deduction/substitution failed:
src/Haar.cpp:58:49: note:   deduced conflicting types for parameter 'const _Tp' ('int' and 'float')
   58 |  return std::max(abs(*pair.first),*(pair.second));
      |                                                 ^
In file included from C:/msys64/mingw64/include/c++/10.1.0/algorithm:61,
                 from src/Haar.hpp:11,
                 from src/Haar.cpp:8:
C:/msys64/mingw64/include/c++/10.1.0/bits/stl_algobase.h:300:5: note: candidate: 'template<class _Tp, class _Compare> const _Tp& std::max(const _Tp&, const _Tp&, _Compare)'
  300 |     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
      |     ^~~
C:/msys64/mingw64/include/c++/10.1.0/bits/stl_algobase.h:300:5: note:   template argument deduction/substitution failed:
src/Haar.cpp:58:49: note:   deduced conflicting types for parameter 'const _Tp' ('int' and 'float')
   58 |  return std::max(abs(*pair.first),*(pair.second));
      |                                                 ^
In file included from C:/msys64/mingw64/include/c++/10.1.0/algorithm:62,
                 from src/Haar.hpp:11,
                 from src/Haar.cpp:8:
C:/msys64/mingw64/include/c++/10.1.0/bits/stl_algo.h:3480:5: note: candidate: 'template<class _Tp> _Tp std::max(std::initializer_list<_Tp>)'
 3480 |     max(initializer_list<_Tp> __l)
      |     ^~~
C:/msys64/mingw64/include/c++/10.1.0/bits/stl_algo.h:3480:5: note:   template argument deduction/substitution failed:
src/Haar.cpp:58:49: note:   mismatched types 'std::initializer_list<_Tp>' and 'int'
   58 |  return std::max(abs(*pair.first),*(pair.second));
      |                                                 ^
In file included from C:/msys64/mingw64/include/c++/10.1.0/algorithm:62,
                 from src/Haar.hpp:11,
                 from src/Haar.cpp:8:
C:/msys64/mingw64/include/c++/10.1.0/bits/stl_algo.h:3486:5: note: candidate: 'template<class _Tp, class _Compare> _Tp std::max(std::initializer_list<_Tp>, _Compare)'
 3486 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
C:/msys64/mingw64/include/c++/10.1.0/bits/stl_algo.h:3486:5: note:   template argument deduction/substitution failed:
src/Haar.cpp:58:49: note:   mismatched types 'std::initializer_list<_Tp>' and 'int'
   58 |  return std::max(abs(*pair.first),*(pair.second));
      |                                                 ^
src/Haar.cpp: In member function 'void haar::Haar::threshold(float*)':
src/Haar.cpp:87:13: error: no matching function for call to 'haar::Haar::sum()'
   87 |  auto s=sum();
      |             ^
src/Haar.cpp:49:7: note: candidate: 'float haar::Haar::sum(unsigned int) const'
   49 | float Haar::sum(const unsigned level) const {
      |       ^~~~
src/Haar.cpp:49:7: note:   candidate expects 1 argument, 0 provided
src/Haar.cpp: At global scope:
src/Haar.cpp:100:28: error: 'Block' does not name a type
  100 | void Haar::threshold(const Block &mu,const Block &sigma) {
      |                            ^~~~~
src/Haar.cpp:100:44: error: 'Block' does not name a type
  100 | void Haar::threshold(const Block &mu,const Block &sigma) {
      |                                            ^~~~~
src/Haar.cpp: In member function 'void haar::Haar::threshold(const int&, const int&)':
src/Haar.cpp:103:12: error: invalid types 'const int[unsigned int]' for array subscript
  103 |   auto m=mu[level];
      |            ^
src/Haar.cpp:104:15: error: invalid types 'const int[unsigned int]' for array subscript
  104 |   auto t=sigma[level];
      |               ^
make: *** [../../compile.mk:69: build/src/Haar.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/Wavelet.cpp:2:
src/Haar.hpp:53:26: error: 'Block' does not name a type
   53 |     void threshold(const Block & mu,const Block & theta);
      |                          ^~~~~
src/Haar.hpp:53:43: error: 'Block' does not name a type
   53 |     void threshold(const Block & mu,const Block & theta);
      |                                           ^~~~~
src/Wavelet.cpp:31:8: error: 'Threshold' in namespace 'haar' does not name a type
   31 |  haar::Threshold thresholds;
      |        ^~~~~~~~~
src/Wavelet.cpp: In member function 'virtual void Wavelet::process(const rack::engine::Module::ProcessArgs&)':
src/Wavelet.cpp:56:5: error: 'thresholds' was not declared in this scope
   56 |     thresholds.set(i,params[i].getValue());
      |     ^~~~~~~~~~
src/Wavelet.cpp:67:23: error: 'thresholds' was not declared in this scope
   67 |     wavelet.threshold(thresholds);
      |                       ^~~~~~~~~~
make: *** [../../compile.mk:68: build/src/Wavelet.cpp.o] Error 1

The v1 branch compiles correctly.

**Comment by jdstmporter** [comment]
v1 branch rebased on top of master (as it should have been) & some other improvements added.  Thank you for the heads-up.
