### ISSUE TITLE
Will not compiled on Windows 10 Pro under MSYS2

### ISSUE THREAD

**Issue by caecos** [jdstmporter/VCV-Plugins#3]
$ RACK_DIR=C:/msys64/Rack-SDK make dist
g++ -std=c++17 -std=c++11 -Wsuggest-override  -fPIC -IC:/msys64/Rack-SDK/include -IC:/msys64/Rack-SDK/dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/customWidgets.cpp.o src/customWidgets.cpp
In file included from src/customWidgets.cpp:10:
src/customWidgets.hpp:30:43: error: in-class initialization of static data member 'std::map<rack::componentlibrary::Orientation, std::__cxx11::basic_string<char> > rack::componentlibrary::SlidePot<O>::backgrounds' of non-literal type
   30 |  static std::map<Orientation,std::string> backgrounds = {
      |                                           ^~~~~~~~~~~
src/customWidgets.hpp:35:43: error: in-class initialization of static data member 'std::map<rack::componentlibrary::Orientation, std::__cxx11::basic_string<char> > rack::componentlibrary::SlidePot<O>::handles' of non-literal type
   35 |  static std::map<Orientation,std::string> handles = {
      |                                           ^~~~~~~
src/customWidgets.hpp:71:43: error: in-class initialization of static data member 'std::map<rack::componentlibrary::Orientation, std::__cxx11::basic_string<char> > rack::componentlibrary::OnOffSwitch2<O>::offs' of non-literal type
   71 |  static std::map<Orientation,std::string> offs = {
      |                                           ^~~~
src/customWidgets.hpp:76:44: error: in-class initialization of static data member 'std::map<rack::componentlibrary::Orientation, std::__cxx11::basic_string<char> > rack::componentlibrary::OnOffSwitch2<O>::ons' of non-literal type
   76 |   static std::map<Orientation,std::string> ons = {
      |                                            ^~~
src/customWidgets.hpp: In constructor 'rack::componentlibrary::ActionButton<S, <template-parameter-1-2> >::ActionButton()':
src/customWidgets.hpp:99:3: error: 'momentary' was not declared in this scope
   99 |   momentary=true;
      |   ^~~~~~~~~
make: *** [C:/msys64/Rack-SDK/compile.mk:69 : build/src/customWidgets.cpp.o] Erreur 1

**Comment by caoliver** [comment]
I see the same thing building on Linux.

**Comment by jdstmporter** [comment]
Should now be fixed; sorry it took so long to respond - major UI redevelopment was going on.
